### ISSUE TITLE
Mark As Watched no longer works

### ISSUE THREAD

**Issue by Bremnerc** [CodeNinjaUK/youtube-subs-grid#108]
Hi,

This was the single extension that made youtube usable for me and now Mark As Watch no longer works, I get

 this error in the console whenever I press the Mark As Watched button: Unchecked runtime.lastError: QUOTA_BYTES_PER_ITEM quota exceeded
![Capture](https://user-images.githubusercontent.com/8465264/68066306-8687ea80-fd0c-11e9-806d-d942ecbdd9f0.JPG)
I am using Chrome Version 78.0.3904.87 and Version 1.19.1 of Subs Grid

Please help/fix this I really loved this extension

**Comment by Rustyb0y** [comment]
You have marked so many videos as watched it has reached the extensions data limit.

Re-install the extension to allow you to mark recent videos as watched again.  Doesn't matter about the old videos as they are not shown unless you load them up

**Comment by borbra** [comment]
Thanks that worked :D 
I think an easier workaround is to just reset the watch history. Though I have not tried this and therefore do not know if it works the same way complete reinstall of the addon worked.
https://i.imgur.com/JV7nAk2.png

**Comment by Rustyb0y** [comment]
Yer, I think that's a better way to do it.  Re-installing doesn't seem to reset all the watched videos.

**Comment by Bremnerc** [comment]
Thank you! That works. However, it seems like I can mark less videos as watched than before. I've used this extension for years and I never ran into this problem. Perhaps a Chrome update reduced the extension data limit. Is there anyway to manually increase this limit for particular extensions?

**Comment by Rustyb0y** [comment]
I don't think so.  I think the original author thought the limit would last for a while.  I did reset my watched through the settings and so far so good.
