### ISSUE TITLE
tooltips no longer work

### ISSUE THREAD

**Issue by hajj3** [CodeNinjaUK/youtube-subs-grid#29]
If the title of the video(s) in your youtube subscriptions is too long you used to be able to hover the cursor over the link and it would give you the full video title, a few days ago this stopped working. Please fix it, thanks :)

Tested using firefox 35 beta 1 and chrome 39.

**Comment by Bulk70** [comment]
I never got around to fixing this directly, but this seems to not be an issue anymore after the last major update.
