### ISSUE TITLE
App no longer working

### ISSUE THREAD

**Issue by Drachlox** [CodeNinjaUK/youtube-subs-grid#31]
It happened yesterday. Suddenly it is showing all the videos, even if i set it to hide viewed videos.
When i select to hide viewed, it just blinks and goes back to showing everything.
Mark as viewed also stopped working. When clicking, the page refreshes (blinks), and the video is still not marked correctly.

Please fix. Not sure i'm ready to go back to how youtube's default page looks.

**Comment by TheLoot** [comment]
Just stopped working for me also. It displays the grid, but watched videos don't hide when set to, and videos can not be marked as watched; nothing happens when clicking those buttons.

**Comment by Bulk70** [comment]
I can confirm I can now see this problem, so it seems YT has rolled out a global change. I'm testing a fix now, and I should be deploying it today at some point.
