### ISSUE TITLE
No longer hiding watched videos

### ISSUE THREAD

**Issue by Lambert2191** [CodeNinjaUK/youtube-subs-grid#32]
I can click hide, show, hide again but it is not hiding any watched videos. I mark "Mark all watched" and then hide, stil showing everything. This is one of my favourite features of subscription grid, hope it gets an update to fix soon

**Comment by Bulk70** [comment]
Thanks for the report, an update fixing this has been uploaded to Google & Mozilla - it should be autoupdating in your browser very soon! :)
