### ISSUE TITLE
SubsGrid only showing the first page - "load more" does nothing

### ISSUE THREAD

**Issue by Drachlox** [CodeNinjaUK/youtube-subs-grid#35]
This happened sometime today. Yesterday it was working fine. 

I opened up the youtube subscription overview and found two video's that i hadn't seen yet, but i knew there were more unseen from yesterday. I therefore clicked "load more" but got nothing.
I then selected to "show" seen video's and it loaded a full page of video's. The two video's it marked as unseen was also on this one page. I then clicked "load more" again, but again this did nothing.

Conclusion:
The functionality of the "load more" button is broken.

Hope for a quick update. :+1:

**Comment by Bulk70** [comment]
Youtube bug I'm afraid, it doesn't work even with the extension disabled :( they normally fix stuff like this pretty quick!

**Comment by Bulk70** [comment]
Closing this now because it seems YT have fixed the issue.
