### ISSUE TITLE
Please fix "mark as watched" button

### ISSUE THREAD

**Issue by ruslanrvd** [CodeNinjaUK/youtube-subs-grid#36]
Screenshot:
![ss 2015-02-18 at 01 29 02](https://cloud.githubusercontent.com/assets/11057026/6244251/8c458336-b772-11e4-8c8a-e3e326bbb354.png)

**Comment by Bulk70** [comment]
Thanks for reporting this, I'm hoping to get a fixed version out in the next few days :)

**Comment by ruslanrvd** [comment]
Thank you for your responsiveness! Your extension - this is the best that has been created for youtube!
