### ISSUE TITLE
Videos marked as watched keeps reappearing

### ISSUE THREAD

**Issue by ruslanrvd** [CodeNinjaUK/youtube-subs-grid#37]
After pressing the "Mark as watched", the video disappears from the list, but after some time it appears again. This problem can be seen in my subscriptions and collections, can fix it?

**Comment by Bulk70** [comment]
I've seen similar issues so I'll look in to this. YT are having problems in this area currently, they aren't properly recording if a video has been watched which they normally do so this is probably related.

**Comment by Bulk70** [comment]
Going to close this now because I've not seen this in a little while - thing YT have fixed things. Let me know if it happens to you again!
