### ISSUE TITLE
Many watched videos still shown and can't be removed from list

### ISSUE THREAD

**Issue by LupinIII** [CodeNinjaUK/youtube-subs-grid#39]
For about two days now I have quite a few videos that are always shown in the grid, although they are greyed and marked as "watched". The "X" for marking them as watched is replaced by a lock symbol (tooltip still says "makr as watched"). Clicking it does not change anything. Clicking "Mark all videos as watched" will empty the list, but after a reload the same videos are there again. This does not apply to all video. A few still have the usual "X" and disappear from the list after watching.
![unbenannt](https://cloud.githubusercontent.com/assets/776804/7101503/e43525b6-e05c-11e4-8626-bb881a39d617.jpg)

**Comment by legitfony** [comment]
I have the same problem.

**Comment by Clainfer** [comment]
Same problem here

**Comment by BananaJack** [comment]
Same here.

**Comment by ruslanrvd** [comment]
If the video has been viewed through YouTube, it is not removed from the list of subscriptions:
![image](https://cloud.githubusercontent.com/assets/11057026/7103193/6dfcd7be-e0b5-11e4-97b5-857dc99879a0.png)

If the video to mark an "X" then it is removed:
![image](https://cloud.githubusercontent.com/assets/11057026/7103192/66e6e780-e0b5-11e4-9126-9457da70448a.png)

**Comment by Bulk70** [comment]
Hi All, I can confirm this bug - I'm aiming to have a fix released for this tomorrow at some point!

**Comment by Bulk70** [comment]
Never mind, was a simple fix - updates should be available on via Chrome in the next hour or so, Firefox will take a bit longer. Thanks

**Comment by Clainfer** [comment]
Perfect!! For me is almost impossible to use youtube without this extension 

Thanks again.
