### ISSUE TITLE
Add On Has Stopped Working

### ISSUE THREAD

**Issue by lawmed** [CodeNinjaUK/youtube-subs-grid#43]
A few days ago the add on stopped displaying the grid. It is as if it is no longer installed, displaying the regular list of subscribed videos. This is when using Firefox 37.0.2

**Comment by Bulk70** [comment]
Apologies for the very slow response on this! Are you still having issues? Can you confirm if you have any other extension that modifies or interacts with Youtube?

**Comment by Bulk70** [comment]
Closing this for now, see the answer for #45 I suspect this may be the same issue.
