### ISSUE TITLE
NOT WORKING

### ISSUE THREAD

**Issue by BadMoonRising** [CodeNinjaUK/youtube-subs-grid#45]
It was a great Add-on, but stopped working for me about a month and a half ago...  Tried removing and re-installing latest version. Still doesn't work. Please help.

**Comment by niebloomj** [comment]
Confirmed. This happened to be starting about a week ago. Just doesn't do anything anymore.

**Comment by Bulk70** [comment]
@BadMoonRising @niebloomj sorry for the slow response here. Can you please both confirm what browser & version you're using? Can you also confirm if you're using any other extensions that modify or interact with Youtube?

**Comment by BadMoonRising** [comment]
Hi,
Thanks for getting back to me.  I'm using FireFox 39.0.   And, yes I'm using the extension "YouTube Grid Search and Preview Player 4.0.3"
But I used both of them together with no problem for a long time...  Hope you can fix it because your add-on is awsome!
 Regards,
Daniel
925-705-1317

**Comment by Bulk70** [comment]
Sorry, I can't replicate this at all. I think possibly the installed addon is corrupted. I can only suggest deleting the subs grid addon from Firefox and re-installing it. Failing that you can also try deleting your profile all together but that will include things like your bookmarks & cookies so isn't ideal (you can export your bookmarks & re-import). 

Unfortunately unless I can replicate the issue there isn't much more I can do I'm afraid!
