### ISSUE TITLE
Hide 'Hide these videos'

### ISSUE THREAD

**Issue by Derpp** [CodeNinjaUK/youtube-subs-grid#46]
The little element to 'Hide these videos' on the top-right corner of each video needs to be realigned or removed. For now I'm using this CSS to make it work.

div.menu-container.shelf-title-cell {
    display: none;
}

**Comment by Bulk70** [comment]
Thanks for this - I've noticed this issue but not had the time this week to release a fix. I'm hoping to do a bugfix release before the end of the weekend
