### ISSUE TITLE
No longer working after youtube grid update

### ISSUE THREAD

**Issue by LupinIII** [CodeNinjaUK/youtube-subs-grid#49]
So after years, youtube has finally come to its senses and went back to the old subscription grid (go figure why we needed this extension). The layout now looks like "subscription grid" made it look before. So you could say we no longer need this extension. But the youtube version lacks two very important features: the ability to hide/unhide watched videos and the ability to remove videos from the list without even watching them.

The issue:
At the current state with "subscription grid" enabled no videos are shown at all in the grid, although there are unwatched ones. It can be seen for a few tenth of a second or so that they are loaded (repeated twice or three times when "subscription grid" tries to fill the list). Could you check if you can give us the hide-features back? Hopefully it's not a total rewrite of the extension but just stripping out of the grid arrangement code and the change of a few CSS-classes/IDs. (and maybe keep the grid code somewhere safe in case youtube decides to make their page more unuseable in the future again).

**Comment by Bulk70** [comment]
I'm just about to release an update that will disable the extension if you have the YT's grid layout. 

Unfortunately YT haven't rolled it out to everyone (or me) yet so this is all I can do until they make a move :disappointed:. Ideally I can at least offer the mark as watched functionality when/if they roll this out to everyone.

**Comment by LupinIII** [comment]
For those having this issue: I logged out of youtube, deleted all youtube related cookies and logged in again. Now I am back to the old feed (where the extension still works as ever). I found now way to enable the new youtube grid, though. So youtube seems to randomly select people for changed features.

**Comment by leopoldw** [comment]
Looks like YT rolled out the new layout for me and I lost the 'mark as watched' functionality (and everything else by the looks of it)... any update on when that will be reinstated for the new YT layout? @Bulk70

**Comment by DrMcCoy** [comment]
It just happened to me as well. :(

**Comment by YannBertrand** [comment]
Is that the new YT grid?
![screen shot 2015-11-18 at 21 51 27](https://cloud.githubusercontent.com/assets/5855339/11253944/96a73c0e-8e3e-11e5-9690-5b4895c79628.png)

Your extension was sooo important to me :'(

**Comment by Nhoise** [comment]
> It looks like my old grid still actually works if you switch to the "list" view, however! 

I just figured this out and was about to post it here myself.
Thank you very much for continuing work on it.
It would be great if you could manage to have the list of videos be endless as well.
Not with the unnecessary 'categories' like Recent, This week etc. which youtube has done now.

**Comment by YannBertrand** [comment]
Yah! It's working by switching to the "list" view!

Wow @Nhoise I didn't know about that... Uninstalled by now.

**Comment by Bulk70** [comment]
New version is out for Chrome and FF now that restores "Mark as watched" to YT's grid, and properly allows people to switch between views. "Classic" mode (full width, no date headers) coming soon!

**Comment by YannBertrand** [comment]
Cool! Looking forward for the classic mode then ;)
