### ISSUE TITLE
Two computers not synced

### ISSUE THREAD

**Issue by JaredSP** [CodeNinjaUK/youtube-subs-grid#50]
So it used to work where if i had clicked on mark as watched on my one computer it would apply to my other computer as well. This no longer works.

**Comment by Bulk70** [comment]
Can you confirm what browser you're using, and what version? This functionality only works for Chrome and uses your Google account to do the sync - can you check you're logged in to the browser on both machines?

**Comment by JaredSP** [comment]
i am logged in on both. using chrome

**Comment by JaredSP** [comment]
Version 45.0.2454.85 m

**Comment by JaredSP** [comment]
?

**Comment by Bulk70** [comment]
I'm sorry I totally forgot about this problem, is it still happening?

**Comment by JaredSP** [comment]
Yeah still an issue. Watched videos are synced but not mark as watched.

**Comment by Bulk70** [comment]
Hi can you go in to your Chrome settings page, click `Advanced sync settings...` and confirm that `Extensions` is ticked? (Or that it's set to sync everything). For instance this is mine: 

![image](https://cloud.githubusercontent.com/assets/417574/11370375/6c706f24-92bb-11e5-836e-a5d35b19dc8c.png)

I'm not really sure what else it could be, the code that sync's data is very much Google's and built in to the core of Chrome - I have no way to debug this :(

**Comment by JaredSP** [comment]
hmm yeah both computers are set to sync everything. both are signed in to the same. i have no clue.

**Comment by DanSmith70** [comment]
Sorry picking up dev on this extension again now - I've changed how history is stored a lot, can you take another look and let me know if it's working if you're still using this extension?

I'll close this for now but please comment it's still broken, thanks!
