### ISSUE TITLE
Videos hiding not working after a Chrome update

### ISSUE THREAD

**Issue by Aslanex** [CodeNinjaUK/youtube-subs-grid#51]
Probably a Chrome update caused, that the history and hiding functions don't work anymore. Here is an error from JS console, which can be related to this problem, something with extension storage.

![snimek obrazovky porizeny 2015-09-06 13 21 34](https://cloud.githubusercontent.com/assets/4586137/9704118/312efb50-549b-11e5-9203-31c03ef5184c.png)

Using version 45.0.2454.85

**Comment by Bulk70** [comment]
Hoping this issue is resolved now?
