### ISSUE TITLE
hiding watched videos not working

### ISSUE THREAD

**Issue by g17-sb** [CodeNinjaUK/youtube-subs-grid#52]
the latest youtube update has completely broken this extension for me. Great job on this, and I don't mean to pressure anybody or anything, but the options to mark videos as viewed and to hide viewed videos are now gone on the subscription page. I'm using iOS 10.10, Chrome Version 45.0.2454.99 (64-bit)
![screen shot 2015-09-26 at 11 19 48 pm](https://cloud.githubusercontent.com/assets/5497807/10121534/525ad0dc-64a5-11e5-9c00-8fe880ef41e7.png)

**Comment by Bulk70** [comment]
Hi this should be fixed with all the updates & new versions - let me know if not!
