### ISSUE TITLE
Feature request: Group videos by date

### ISSUE THREAD

**Issue by Blasz** [CodeNinjaUK/youtube-subs-grid#53]
I recently had youtube's standard subscription grid view and have now been moved back to list view.
I noticed that youtube's grid view grouped videos by date, allowing one to easily recognise the general upload time of the videos.

I believe it grouped them into something like:

* Today
* Yesterday
* 2 days ago
* Earlier this week
* Before this week

Just displaying a header above each group of videos

Would this be a welcome feature if I went ahead and implemented a PR for this?

**Comment by Bulk70** [comment]
Sounds like a very useful feature, by all means submit a PR and I'll take a look :)

**Comment by LEOXDmtar** [comment]
What's the point of having a browser extension that gives you a grid view when YouTube is implementing a grid view (which can even toggle between list and grid) themselves?

**Comment by Bulk70** [comment]
Source? I just see the normal list still. At any rate this extension is over 2 years old and was designed for when YT didn't have a grid view. 

I know they've been testing a grid view for a while but it's not been universally released yet, and in fact the extension is designed to disable it's self for users who have YT's grid view. Once the grid becomes universal I may modify the extension to add missing functionality (if any) to the grid, or just retire it entirely - not sure yet.

**Comment by LEOXDmtar** [comment]
Source: I'm one of these: www.g.co/topcontributor

The rollout of the grid actually just was stopped because bugs were discovered, so your extension has a couple more days still: weekends are the only time when the engineers are allowed to sleep ;)

**Comment by Bulk70** [comment]
Awesome, cool if the need for the extension isn't there anymore I'll see what the options are when the time comes I guess :)

**Comment by DrMcCoy** [comment]
YouTube's grid view is missing a way to mark videos as watched, though, and it doesn't remove already watched videos from the grid. This makes YouTube's own grid completely useless. :(
