### ISSUE TITLE
As of today (11-18-15) the ability to hide videos doesn't work all of a sudden

### ISSUE THREAD

**Issue by MattKimura** [CodeNinjaUK/youtube-subs-grid#54]
Seems like Youtube's site updated, because this extension was working last night. But today I can't seem to hide videos any longer. Perhaps it was Chrome that updated?

Either way, this is one of my fav extensions, hope to have this fixed!

**Comment by kancana** [comment]
I'm also having the same problems...  *sigh*

**Comment by Nhoise** [comment]
Bulk70 said he'll be working on an udate soon, but in the meantime you can switch to list view.
>It looks like my old grid still actually works if you switch to the "list" view, however!

**Comment by kancana** [comment]
Thanks, Nhoise!

**Comment by Bulk70** [comment]
New version is out for Chrome and FF now that restores "Mark as watched" to YT's grid, and properly allows people to switch between views. "Classic" mode (full width, no date headers) coming soon!

**Comment by kancana** [comment]
Thanks!!!!
