### ISSUE TITLE
CHROME mark as watched etc

### ISSUE THREAD

**Issue by silat** [CodeNinjaUK/youtube-subs-grid#55]
I think YT updated. This seems to have caused yt sub grid to not work properly. 
1. Cannot see the buttons for "mark videos watched" etc.
2. Subscriptions list is broken up into days.

**Comment by kancana** [comment]
Yes, same thing is happening to me...

**Comment by Nhoise** [comment]
Bulk70 said he'll be working on an udate soon, but in the meantime you can switch to list view.
>It looks like my old grid still actually works if you switch to the "list" view, however!

**Comment by silat** [comment]
Thanks for the tip. And I want the developer to know that I am not complaining. Love the extension and just wanted to let him know the issue. Is there a way to donate?

**Comment by silat** [comment]
Thanks for the fix Bulk :)

**Comment by Bulk70** [comment]
New version is out for Chrome and FF now that restores "Mark as watched" to YT's grid, and properly allows people to switch between views. "Classic" mode (full width, no date headers) coming soon!
