### ISSUE TITLE
Increase limit of stored watched videos

### ISSUE THREAD

**Issue by Droyk** [CodeNinjaUK/youtube-subs-grid#56]
Plz make this extension more powerful whenever i try to hide videos it automatically unhide videos those hide before so plz do something about these 

and new update of chrome make it more unbearable to hide the videos properly plz make it more efficident thanxxx

Sorry for my bad English i am not your typical native English speaker

**Comment by Bulk70** [comment]
I've just released a new version that _should_ fix this issue. Please let me know if it's still happening/

**Comment by Droyk** [comment]
You are about too read a bad english. and i am really sorry about it i am not native english speaker  

Thanxx it worked but as i said the only problem in this is i have a huge subscription list and that means there are loads of videos everyday so when i click mark all videos as watched sometimes it hides and sometimes it unhides all the videos that have been hidden 
this problem partially solved in the new update you have just released 

But this updates also didn't solved it completely i have huge collection of videos so i just tried your new version it only hides Today and yesterday videos but your new updates doesn't hide the recent videos

it partially hides it but when we refresh the page or go to the subscription list view  it unhides them

so this the problem right now . and this [problem is not new. as long as i remember this problem is started when u made the extension.

**Comment by Bulk70** [comment]
Ah ok I think I know what this issue is. The extension has a memory limit of 200 videos, once you have more than that "watched" it'll remove the oldest from the list. I'm going to see if I can raise the limit, that should fix your issue.

**Comment by Droyk** [comment]
>The extension has a memory limit of 200 videos
I'm going to see if I can raise the limit, that should fix your issue.

**Plz raise the limit too 1000 to 1200 i know its hard  but plz
and if you cant do it to 1200 then plz raise the limit atleast 8000**

i am saying this because youtube new grid can show you atleast **8000 to 10000 videos** 
i am saying this because i did some research today and see how much can YouTube grid can actually go and **it really surprised me a lot it can go up to 6 to 7 years of content.** for doing that my browser crashed 5 times and i have clicked my mouse more than 20000 times i think today because of the youtube grid 
**if you don't believe me then try own your own i am really sure it will eat up your whole day**

**Comment by Bulk70** [comment]
Wow thats a lot! So with out confusing you with technical stuff I can easily raise the limit to 400 in the next version but more than that is actually a massive challenge. Chrome and Firefox both limit how much I can store, and the limit sadly isn't very big. 

I've got a few ideas for different things I can do but I'm sad to say its unlikely I'll be able to support that many videos any time soon, I'm sorry :disappointed:

**Comment by Droyk** [comment]
**Ahh don't worry about the technical stuff i am all into it.** i know it will be hard i mean in a certain level 
but plz you can have a week or two but plz atleast raise a limit too 600 on 600 range i will never try to load more videos. and everyone will be pleased  

**Some Noobs Questions** 

Can you plz tell something you just said 
> Chrome and Firefox both limit how much I can store, and the limit sadly isn't very big.

Why you store those videos on the first place why cant just hide or remove them for e.g. take any adblocker i have tried that on youtube that thing can go up to 1500 to 1600 or maybe more .

**So Why You Cant Just Remove Them**

**Comment by Bulk70** [comment]
So I use an internal Chrome function that syncs the videos you've watched over all the desktop devices you use, using your Google account. The problem is that this method has a hard limit of *8kb* in which to store the user's watched history - that roughly translates to 400 or so videos, and is a hard limit. 

To store more I need to find a different way of storing them. I think what I'm going to do is keep the most recent 400 videos synced as we do now, but also have a "long term" history that _isn't_ shared with your other devices and can be significantly bigger (up to 100,000 even).

I have a bunch of other stuff I need to work on first so I don't know when this will be done, but it's on the list for sure!

**Comment by Droyk** [comment]
I don't use the sync function actually but i really like the idea of syncing it. 
As you said store only 400 to 500 videos synced and **store all the other history to the user computer (HD,SSD).**

**i don't care if it takes space i only care about hiding the videos.** 

so when will you release your next big update i have really high hope for your next big update

**Comment by Droyk** [comment]
So [Bulk](https://github.com/Bulk70) when you are going to release your next big update 
i am waiting here patiently but really cant wait it

**Comment by Bukkithead** [comment]
If it's difficult to increase the limit of videos stored, is it instead possible to add an option to limit how many videos are loaded on the subscriptions grid? This is only a problem for me if YouTube loads subscriptions past a certain point (at which point the 'Load more' button is greyed out). Even then, if I refresh the page then for whatever reason it doesn't keep loading videos as far as it can. If the amount it loaded was limited (i.e. disabling whatever the 'Load more' button does), then the old videos wouldn't be showing up on my feed and I wouldn't be having this issue. Personally, I have absolutely no need to be viewing 3+ week old videos anyway, so I wouldn't miss that functionality.

**Comment by FKasa** [comment]
JS Dev here. I could give you some suggestions and contribute if I find the time.

How do you store watched videos, using IDs?
LS-VPyLaJFM
jNQXAC9IVRw

Are you storing those in a large string and parsing the list by splitting every 11 characters?

Have you thought about using a compression library?

**Comment by DanSmith70** [comment]
Good news - it's taken me a lot longer than I wanted but this feature is finally done. I've just uploaded a new version that increases the _synced_ videos (watched videos synced between devices) to **2,000** and a further **3,000** videos are stored locally on the device for a total of **5,000**. I can increase the local limit much higher but I'm worried about performance with that many videos recorded - for me this was enough to store about 2 years worth of videos so I think it'll be enough.

**Comment by Droyk** [comment]
[**@DanSmith70**](https://github.com/DanSmith70) commented on [Mar 29, 2016, 2:09 AM GMT+5:30](https://github.com/CodeNinjaUK/youtube-subs-grid/issues/56#issuecomment-202572438 "2016-03-28T20:39:37Z - Replied by Github Comment Enhancer"):
> Good news - it's taken me a lot longer than I wanted but this feature is finally done. I've just uploaded a new version that increases the _synced_ videos (watched videos synced between devices) to **2,000** and a further **3,000** videos are stored locally on the device for a total of **5,000**. I can increase the local limit much higher but I'm worried about performance with that many videos recorded - for me this was enough to store about 2 years worth of videos so I think it'll be enough.

Really Thanxx @DanSmith70  Now I can hide my videos without any worries  at all :relaxed: Really Thanxx :smile:
