### ISSUE TITLE
Donate

### ISSUE THREAD

**Issue by silat** [CodeNinjaUK/youtube-subs-grid#57]
Do you take donations?

**Comment by Bulk70** [comment]
Aha no, thank you very much though! I do this because I enjoy it and want to use the extension as well ;)

If you really want you can make a donation to a charity, that would make me much happier :)

**Comment by silat** [comment]
Ok :) I gave to my local Planned Parenthood.

> On 11/22/2015 11:35:54 AM, Daniel Smith (notifications@github.com) wrote: 
> > Aha no, thank you very much though! I do this because I enjoy it and
want to use the extension as well ;) 
> 
> If you really want you can make a donation to a charity, that would make
me much happier :) 
> 
> > On 22 Nov 2015, at 18:31, silat <notifications@github.com> wrote: 
> > 
> > Do you take donations? 
> > 
> > - 
> > Reply to this email directly or view it on GitHub. 
> > 
> 
> 
> --- 
> Reply to this email directly or view it on GitHub: 
>
https://github.com/CodeNinjaUK/youtube-subs-grid/issues/57#issuecomment-1587
92393 
>
