### ISSUE TITLE
Less of an issue, more of a request; Is there any way to format the grid to what it was pre-update?

### ISSUE THREAD

**Issue by 1500lego** [CodeNinjaUK/youtube-subs-grid#58]
Of course, I don't hate the new "sorted by day, week and month" grid that youtube have implemented, but I'd rather it just be like what the grid was before, simply all grouped together as one grid sorted by upload date, rather than a bunch of rows with bulky dividers which provide no use to me...

If anyone could provide any further information on how to aid my request/preference it would be much appreciated, though if I were to suggest an improvement, I would suggest an option between the modern and classical subscriber grids, but that's just me.

cheers

**Comment by Bulk70** [comment]
Short answer is yes! :smile: I'm working on it right now, and I'm calling it "Classic" mode. It'll be full width with no date separators (as well as the current mark as watched stuff). I don't want to make promises I can't keep but hopefully it'll only be a matter of days :)

**Comment by 1500lego** [comment]
Ah, that's great news... exactly the answer I was hoping for.
