### ISSUE TITLE
Bug: Videos aren't hiding automatically after watching the video 

### ISSUE THREAD

**Issue by Droyk** [CodeNinjaUK/youtube-subs-grid#60]
As the title says videos are not automatically hiding after watching the video you have to hide it manually.

This issue is not came today it is from when YouTube changes its old layout to the grid one and you release the updates in those updates  you didn't add the functionality to hide the videos automatically .

So plz add it to the next one .****but if you are really not planning to adding it. 
Then its okay too don't add it we can do it manually too. thanxx****

**Comment by Bulk70** [comment]
Thanks for reporting! This is the same as issue #63 so closing this one
