### ISSUE TITLE
Marking as Watched After Adding to Watch Later

### ISSUE THREAD

**Issue by TheLoot** [CodeNinjaUK/youtube-subs-grid#61]
It's been a persistent thing, but after using the Watch Later button, no method of marking as watched works until you reload the page. I assume it's something to do with the button and label changing after pressing it.

**Comment by Bulk70** [comment]
Hm ok thanks, I'll look in to this!

**Comment by TheLoot** [comment]
Not sure if you changed something with it since, but the "Mark All" will hide them now, though they will return after reloading the page.
