### ISSUE TITLE
firefox 30

### ISSUE THREAD

**Issue by drifterDS** [CodeNinjaUK/youtube-subs-grid#62]
Is this going to be updated to work in FF 30. ?

**Comment by Bulk70** [comment]
It's not likely to be honest - the extension is making use of some internal features that require at least FF 34. Whats the reason you're using such an old version if I may ask?

**Comment by drifterDS** [comment]
My other addons don't like versions over 30.

-----Original Message-----

**Comment by drifterDS** [comment]
BTW doesn't work in FF35 either, says not available for 36.0

-----Original Message-----

**Comment by Bulk70** [comment]
Sorry Mozilla marked it as 38+ by default - I've updated the listing to be 34+. Closing this for now because I can't really support less than v34 at this time, I'm sorry!
