### ISSUE TITLE
Video isn't marked as watched when clicking or visiting the link

### ISSUE THREAD

**Issue by Csapi007** [CodeNinjaUK/youtube-subs-grid#63]
Hy
Awsome updates, however a functionality that has worked before isn't working with the newest release: when you open a video by dragging the link to the tab bar the video isn't removed from the list.
Chrome 46.0.2490.86, SGfYT 1.16.0

**Comment by abyssis** [comment]
I've noticed the same thing using the scroll button to open up new videos.

**Comment by Bulk70** [comment]
Confirmed! Think I may have accidentally removed this functionality, but I'll be bringing it back in an update very soon.

**Comment by abyssis** [comment]
Thank you!

**Comment by DanSmith70** [comment]
This functionality should be working now, but please let me know if it's still broken for you.
