### ISSUE TITLE
Too much thumbnails loaded at once with new update

### ISSUE THREAD

**Issue by Nhoise** [CodeNinjaUK/youtube-subs-grid#64]
The new update completely locks up my browser for a good 10-20 seconds when loading my subs page.
Less so on Youtube Grid mode, but Classic mode is pretty extreme.
Over 200 thumbnails are loaded at once.

My suggestion would be to reduce the number heavily, like in the previous version (before youtube broke this wonderful addon)

**Comment by Bulk70** [comment]
Hm the addon performs the same actions it used to but YT do seem to be returning more videos since the update. I have an idea how to fix this (with a setting) in an upcoming release (hopefully in the next few days)

**Comment by Nhoise** [comment]
Yeah it seems like this is normal youtube behavior now.
The default grid mode returns just as much videos with or without this addon installed.
Just a problem with my underpowered laptop then, not really caused by this addon.
