### ISSUE TITLE
THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU

### ISSUE THREAD

**Issue by Drachlox** [CodeNinjaUK/youtube-subs-grid#65]
Again.. thank you SO much for the latest update of the addon that added the "classic subs grid" option. 
I was sure the old version was gone forever after Youtube decided to change shit again. 

And of course, thank you for making and updating this addon. It's great. 
Yes, some users gets pissy when youtube "fixes" stuff and it gets broken, but please just ignore them. 
If they can't understand that a 3rd party addon needs tweaking whenever Youtube changes shit then they're acting like spoiled brats, and who cares about spoiled brats anyway?!.. 

So finally.. THANKS! :+1:

**Comment by Droyk** [comment]
Yup thanxx for his hard work even i thought we will never see this project shine again but see we thanxx to this hardworking developer

**Comment by Bulk70** [comment]
Thankyou for saying so :grinning:!
