### ISSUE TITLE
Videoindicator still counting marked Videos

### ISSUE THREAD

**Issue by macearl** [CodeNinjaUK/youtube-subs-grid#66]
Hi,

probably not really a big thing (or really that important) but i just noticed that the Indicator next to the Subscriptions button is still counting videos that i marked as watched.

Its just a bit annoying that it always shows that there are tons of new videos when in fact there are none.

Here's a Screenshot of what i mean:  ![Image of Indicator](http://i.imgur.com/UpYWlnh.png?1)

I think it could possibly be connected to viewed videos not being marked as watched automatically, as im guessing as of now only the list for the addon gets updated but not whatever kind of list youtube uses

**Comment by abyssis** [comment]
Same issue here.

**Comment by Bulk70** [comment]
When using the "mark as watched" option it's not marked as far as YT is concerned, only the extension knows it's "watched" unless you actually click through the video (and watch part of it). The number you're referring to is counting the unwatched videos from YT's perspective and unfortunately there's nothing I can do to control it, sorry :disappointed:.

**Comment by Droyk** [comment]
if you guys are really irritated by that then there is a way you can hide that by using any adblocking software and use block element and bam its dissappear
