### ISSUE TITLE
Minor bug: Video's not being marked as watched when using "open in new window"

### ISSUE THREAD

**Issue by Drachlox** [CodeNinjaUK/youtube-subs-grid#67]
This is a variant of other reported bugs in the latest version, but i thought i'd mention it.
I usually open my incoming video's by rightclicking them and "open in new window" (or using the shortcut that does the same). In earlier versions (before youtube messed it up.. again), video's that i opened this way was being marked as watched. In the latest version they aren't and i therefore have to manually mark them as watched. 

Personally i think this is a minor bug as it's not breaking the addon. It's just a minor inconvenience. 

Thanks for a great addon. :)

**Comment by Csapi007** [comment]
Can be merged with #63.

**Comment by Bulk70** [comment]
Thanks for reporting, confirmed this is the same bug as #63
