### ISSUE TITLE
I really like the "classic mode", as I mentioned the other day, but I cannot bare how the videos balance out to be centred!

### ISSUE THREAD

**Issue by 1500lego** [CodeNinjaUK/youtube-subs-grid#68]
How the videos in each row always want to be centred in the middle of the page makes it awfully frustrating in order to clear a bunch of videos I don't want in my sub feed, since the X buttons keep moving across the screen...

I would suggest the system before where the videos are all left-biased so I can spam-click the X button to clear a few in a row rather than repositioning the mouse over and over... It's a small little thing but it makes my viewing sessions a wee bit of a hassle!

Cheers though, I'm glad you've taken the time to sort this out with all the date dividers and everything!

**Comment by Bulk70** [comment]
Totally agreed - I need to work out better styling for sure, it's high on the list!

**Comment by 1500lego** [comment]
Ah, once again, you're living up to the high standards of a good developer! Thank you for the quick response.
