### ISSUE TITLE
Subscription Grid not working at all

### ISSUE THREAD

**Issue by oceanotter** [CodeNinjaUK/youtube-subs-grid#69]
Using Windows 7

Chrome latest version 46.0.2490.86 m

It just stopped working entirely, tried removing, and reinstalling it even chrome itself, but it keeps having the same issue.  Is there a way I can provide you a more detailed log of information to help troubleshoot this?

**Comment by abyssis** [comment]
Pretty strange since everything seems to be working fine here, apart from the issues that have already been flagged by @Bulk70.

Windows 8.1
Chrome 46.0.2490.86 m (64-bit)

**Comment by Droyk** [comment]
On windows 7 x64  
i don't have any problem at all
Chrome Version 46.0.2490.86 m (64-bit)
maybe its the problem on your side try too see if there are any other plugins conflicting with this one

**Comment by DanSmith70** [comment]
Sorry I missed this - closing for now, but please re-open if you still have this issue and I'll investigate.
