### ISSUE TITLE
Don't hides the video after viewing

### ISSUE THREAD

**Issue by ruslanrvd** [CodeNinjaUK/youtube-subs-grid#70]
Don't hides the video after viewing. It helps only through the hide button, or reload the page. If possible, please make the hidden video immediately after its opening.

**Comment by DanSmith70** [comment]
This should be fixed in the most recent version (going live soon) sorry for the delay!

**Comment by Droyk** [comment]
[**@DanSmith70**](https://github.com/DanSmith70) commented on [Mar 29, 2016, 2:14 AM GMT+5:30](https://github.com/CodeNinjaUK/youtube-subs-grid/issues/70#issuecomment-202573628 "2016-03-28T20:44:01Z - Replied by Github Comment Enhancer"):
> This should be fixed in the most recent version (going live soon) sorry for the delay!

Thanxx For Your Hardwork @DanSmith70
