### ISSUE TITLE
Filter videos

### ISSUE THREAD

**Issue by YannBertrand** [CodeNinjaUK/youtube-subs-grid#72]
It would be great to add some config page to filter the videos that appears on the subs page. For example, I do not watch videos about Hearthstone, I would like to hide videos about this game (by looking into the title) or mark them as watched whenever some appear. Another example: I do not want some playlists to appear on my feed.

I know it's a big project but I think it would be interesting for all of us ;).

**Comment by DanSmith70** [comment]
Good suggestion - merging with #44. No idea if this will ever happen in the form of an extension (see the other issue) but I'd love to do it.
