### ISSUE TITLE
Not working because YT updated

### ISSUE THREAD

**Issue by silat** [CodeNinjaUK/youtube-subs-grid#73]
Hi,
 I think an update is needed again:)

**Comment by abyssis** [comment]
What exactly isn't working for you?

**Comment by silat** [comment]
No buttons to mark all videos.  I tried to reply to your email but it was rejected.

**Comment by abyssis** [comment]
I'm not seeing any issues on my end.

**Comment by silat** [comment]
It was not working on FF, Chrome and Chrome Dev and I cleaned out all cookies etc.
It was still not working.
Now it is working.
Sorry for bothering you. I appreciate all you do and love the extension. 
Thanks so much.
