### ISSUE TITLE
[request] All activity?

### ISSUE THREAD

**Issue by feelingok** [CodeNinjaUK/youtube-subs-grid#74]
Since youtube removed the feature to see videos that had been liked/favorited/playlisted by your subcriptions, Would it be possible to re-impliment it with this add-on?
This add-on was extremely useful to me before youtube decided to remove the activity feature

**Comment by DanSmith70** [comment]
Sorry I'm fairly certain this isn't possible - the addon works by modifying data already on the page and as they've removed this data all together my hands are tied.
