### ISSUE TITLE
Auto loading issue with no recent unwatched videos.

### ISSUE THREAD

**Issue by HighFromCost** [CodeNinjaUK/youtube-subs-grid#83]
Hey, I'm running on chrome and recently discovered an annoying little issue. Just to mention first, I have auto load as you scroll turned off, and hide watched videos turned on. 

I had watched all my recent videos so there was nothing to load in my subscription page and for some reason this made the auto loader kick in until it had a video(s) to show. If I remember correctly it started with a few videos from 2 weeks ago, and then stopped (it stopped auto loading because it now had at least one video displayed as unwatched). Not wanting any videos to show, I marked all of them as watched, once the last one was gone the auto loader kicked in again until it found the next set of unwatched videos (just older ones that youtube had forgotten I watched). Again I marked all as watched and again the auto loader kicked in, I kept doing this a few more times to see if it would stop, and I didn't. I was soon loading videos from over a year ago, each time a new batch of videos would pop up the auto loader would be satisfied and stop, then I would mark them all as watched (I was using the mark all videos as watched button rather than doing it manually by this point) and it would continue to load older and older videos. At this point I gave up marking the videos as watched figuring it would not stop, I refreshed the subscription page and it loaded to the batch of old videos I had stopped on. 

As you can imagine this took a bit of time to load, seeing as it had to load through a lot of watched videos before it finally reached a point where it found something to display. What I did to combat this was go back an mark one of my most recent videos as unwatched and reloaded the page, this seemed to satisfy the auto loader and it only displayed the one video without going as far back as before. 

I would hate to have such a long loading process happen every time I load my subscription box without any new videos and i'm sure it's not an intended function of the app. Keeping one new video unwatched works for now but I just wanted to bring this issue to your attention. 

One last important detail; I know I have recently had an empty subscription box with out this issue happening, but I just recently subscribed to a new channel and it loaded a few of their older unwatched videos on my sub page. I believe me subscribing to this channel and the older videos that caused to be shown in my sub bow might have triggered the auto loader to start searching for older and older videos once all my current videos had been watched.

I'm not sure if this issue will stop once I get some new videos coming into the sub box, but I just though I'd let you know that this weird bug is possible, maybe a cap to how fat back the auto loader will go could be added, I know youtube "forgets" what videos you've watched after a couple weeks (i know those were the first batch of videos that were 2 weeks old I mentioned earlier) it first so I'm not sure if it's be possible. Anyway thanks for reading!

Here's a few screen caps of what my sub box looked like when it had the really old videos loaded (it's the top and bottom half of the page, had to scroll down through a few "older"s before the videos started showing)

<img width="1180" alt="screen shot 2016-04-05 at 2 58 33 am" src="https://cloud.githubusercontent.com/assets/18282419/14278027/8862abca-fada-11e5-96ee-580ba4147935.png">

<img width="1178" alt="screen shot 2016-04-05 at 2 58 55 am" src="https://cloud.githubusercontent.com/assets/18282419/14278018/80dac57c-fada-11e5-8ada-395c5b95e4fe.png">

**Comment by Droyk** [comment]
**Issue already reported in #82 
You are about to read some bad English. and I am really sorry about it. I am not a native English speaker.**
Right now the only thing You can do is watch every video and don't watch only one video so the subscription list don't load any further to load the videos

**Comment by HighFromCost** [comment]
Yup, that's what I figured out works as well Droyk. Glad we've both come across the same thing. (I can totally understand you're english by the way!)

**Comment by Droyk** [comment]
Hey @HighFromCost how are U ? It seems like youtube got Updated and it solved our problem so can you plz close this issue now thanxx

**Comment by HighFromCost** [comment]
@Droyk No problem, thanks for the heads up! :D
