### ISSUE TITLE
Watched not hidden, Load More button non-functional

### ISSUE THREAD

**Issue by TheLoot** [CodeNinjaUK/youtube-subs-grid#89]
Only works after Show More text in bottom right is clicked, which clears up both issues until page reload.

**Comment by Billy364** [comment]
Can confirm same thing is happening to me.

**Comment by Freakofspeed** [comment]
Can confirm same thing is happening on my computers  and laptop here.

**Comment by DanSmith70** [comment]
Yep looks like YT have tweaked something so this is broken. I'll try and get a fix out in the next day or so.

**Comment by jamescousins** [comment]
Thanks Dan - same issue on windows 10 and osx.

**Comment by Meeems** [comment]
Yay, thanks Dan, please fix soon, very annoying...almost as annoying as windows 10..gawd i wish i went back when i had the chance to my previous windows...sniffle'...

**Comment by DanSmith70** [comment]
The new version which is live for Chrome and soon for FF should fix this issue. Thanks!

-- Dan

**Comment by DanSmith70** [comment]
Closing this, looks like we're back in business. Thanks for the reports guys!
