### ISSUE TITLE
hide button

### ISSUE THREAD

**Issue by originalmoonbear** [CodeNinjaUK/youtube-subs-grid#90]
hide button not working all vids show as watched old vids re-appear..

**Comment by j3r03nq** [comment]
Same here, reinstalled just to be sure but invisibility cloak is definitely broken.

**Comment by DanSmith70** [comment]
The new version which is live for Chrome and soon for FF should fix this issue. Thanks!

-- Dan

**Comment by originalmoonbear** [comment]
hi thanks for the reply, i have ff.. i dont mind the wait if i know the fix is coming, google really are retards to have the page setup the way they do and i appreciate the fix and effort ..cheers..del


________________________________

**Comment by DanSmith70** [comment]
Awesome, hopefully the FF version will be live soon! Closing this bug now as I think this is all fixed.
