### ISSUE TITLE
"Show More" text/button not gone in "Classic Sub Grid" mode.

### ISSUE THREAD

**Issue by jacobmix** [CodeNinjaUK/youtube-subs-grid#91]
Make it so the normal "show more" YouTube button doesn't need to be clicked?
The button has always annoyed me since it hides videos.
(Tho without this it extension, it hides videos multiple times. Because it loads in groups/days/weeks.)
One of the reasons i got this extension was so i wouldn't miss videos anymore because of it.
Gladly i only have to press it once now. But it's still kind of a pain that it's there.
Button in question: http://prntscr.com/bt24mj
Sorry if this is already known. Didn't see a thread just addressing this. Love the extension so far btw!

**Comment by DanSmith70** [comment]
This should be fixed in the most recent version which went out an hour or so ago - you may not have it yet. Apparently this may just be a YT bug but I fixed it for them anyway ;)

-- Dan

**Comment by jacobmix** [comment]
Thank you. I'll restart chrome, and see if it updates.
I'll be sure to close this issue tracker when i've confirmed it's been fixed.
Thanks for the quick answer.

**Comment by jacobmix** [comment]
Nothing seems to be changed yet. On version 1.19 http://prntscr.com/bt2itx
Not sure if that's the updated version since i didn't check the version when i installed.
It might just take a while for the update to go out, and that.

**Comment by DanSmith70** [comment]
Hmm, 1.19 is definitely the latest version and should fix the issue - it does for me anyway. It's possible you're seeing a different version of the subs feed to me and YT are doing a test on you. If you still have this issue can you try logging out of YT and clearing your cookies?

**Comment by jacobmix** [comment]
New day for me. Seems fixed. I now have version 1.19.1 http://prntscr.com/bt8xv8
Thanks for being so responsive. Now that the issue have been fixed. I'll be closing this.
