### ISSUE TITLE
New update not working without scrolling.

### ISSUE THREAD

**Issue by HighFromCost** [CodeNinjaUK/youtube-subs-grid#92]
The latest update is great, good to see the subscription page back to normal again! The only problem is that nothing starts working until I scroll to the bottom of the page. Upon refreshing/navigating to the subscription page is seems like the extension doesn't kick in, watched videos are all still there along with the "show more" options. Assuming I don;t scroll down it will stay this way. It isn't until I scroll to the bottom of the page that the extension seems to kick in and start working. 

Here's how it looks when I first refresh/navigate to the sub page:
<img width="1178" alt="screen shot 2016-07-15 at 1 25 54 am" src="https://cloud.githubusercontent.com/assets/18282419/16868264/74870178-4a2b-11e6-9135-b2982f1a1400.png">

Here's scrolling to the bottom:
<img width="1178" alt="screen shot 2016-07-15 at 1 26 08 am" src="https://cloud.githubusercontent.com/assets/18282419/16868265/79b6d34e-4a2b-11e6-9ddd-e7e921b6611e.png">

And then it kicks in:
<img width="1180" alt="screen shot 2016-07-15 at 1 26 12 am" src="https://cloud.githubusercontent.com/assets/18282419/16868272/7e872ba8-4a2b-11e6-9741-b543926485eb.png">

**Comment by DanSmith70** [comment]
Ahh, oops! I know why this is happening and I can replicate it. I'll work on a fix and get something out in the next hour or so, sorry about that.

**Comment by DanSmith70** [comment]
OK fix for this should be live in the next 30 minutes or so! Let me know if this is still happening once you have v1.19.1. Thanks for the report!

**Comment by HighFromCost** [comment]
Working perfectly now with 19.1 :D Amazing work man, seriously, thank you!!
