### ISSUE TITLE
Videos losing watched status

### ISSUE THREAD

**Issue by TheLoot** [CodeNinjaUK/youtube-subs-grid#95]
My sub feed's been showing a lot of videos that had been previously hidden lately, even after I had removed and re-added the extension,

Happens whether I actually "watch" a video or just mark as such through Subs Grid.

**Comment by Eiion** [comment]
Same here. Instead thumbnails now have a red line at their bottom which is either complete from left to right or only like 1/6th starting from the left - no idea what's the difference.

**Comment by DanSmith70** [comment]
Hey guys - see #96
